version: '3.8'

services:
  ai-devops-framework:
    build: .
    container_name: ai-devops-framework
    volumes:
      - ./src:/app/src:ro
      - ./outputs:/app/outputs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    
  ai-devops-dev:
    build: .
    container_name: ai-devops-framework-dev
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    command: ["python", "demo.py", "--example", "full_stack_development"]
    profiles:
      - dev